---
apiVersion: v1
kind: Service
metadata:
  annotations:
    jkube.eclipse.org/git-commit: be601433c11f023dcf3981154937f2473db83d7e
    jkube.eclipse.org/git-url: https://dev.azure.com/ThiqahDev/Bookstack/_git/Bookstack
    jkube.eclipse.org/git-branch: be601433c11f023dcf3981154937f2473db83d7e
  labels:
    app: consumer-management-svc
    provider: jkube
    version: 1.0-SNAPSHOT
    group: com.getsettle
    app.kubernetes.io/part-of: com.getsettle
    app.kubernetes.io/managed-by: jkube
    app.kubernetes.io/name: consumer-management-svc
    app.kubernetes.io/version: 1.0-SNAPSHOT
  name: consumer-management-svc
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: consumer-management-svc
    provider: jkube
    group: com.getsettle
    app.kubernetes.io/name: consumer-management-svc
    app.kubernetes.io/part-of: com.getsettle
    app.kubernetes.io/managed-by: jkube
  type: ClusterIP
