---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    jkube.eclipse.org/git-commit: 3df5fe2a84862b9a36386af54d47e7f5eaf1fd08
    jkube.eclipse.org/git-url: https://dev.azure.com/ThiqahDev/Bookstack/_git/Bookstack
    jkube.eclipse.org/git-branch: 3df5fe2a84862b9a36386af54d47e7f5eaf1fd08
  labels:
    app: consumer-management-svc
    provider: jkube
    version: 1.0-SNAPSHOT
    group: com.getsettle
    app.kubernetes.io/part-of: com.getsettle
    app.kubernetes.io/managed-by: jkube
    app.kubernetes.io/name: consumer-management-svc
    app.kubernetes.io/version: 1.0-SNAPSHOT
  name: consumer-management-svc
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: consumer-management-svc
      provider: jkube
      group: com.getsettle
      app.kubernetes.io/name: consumer-management-svc
      app.kubernetes.io/part-of: com.getsettle
      app.kubernetes.io/managed-by: jkube
  template:
    metadata:
      annotations:
        jkube.eclipse.org/git-commit: 3df5fe2a84862b9a36386af54d47e7f5eaf1fd08
        jkube.eclipse.org/git-url: https://dev.azure.com/ThiqahDev/Bookstack/_git/Bookstack
        jkube.eclipse.org/git-branch: 3df5fe2a84862b9a36386af54d47e7f5eaf1fd08
      labels:
        app: consumer-management-svc
        provider: jkube
        version: 1.0-SNAPSHOT
        group: com.getsettle
        app.kubernetes.io/part-of: com.getsettle
        app.kubernetes.io/managed-by: jkube
        app.kubernetes.io/name: consumer-management-svc
        app.kubernetes.io/version: 1.0-SNAPSHOT
    spec:
      containers:
      - env:
        - name: APP_CONFIG_PATH
          value: /etc/config
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        envFrom:
        - configMapRef:
            name: consumer-management-svc-config
        image: 7uss770/settle:355605
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health
            port: 9090
            scheme: HTTP
          initialDelaySeconds: 180
          successThreshold: 1
        name: consumer-management-svc
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health
            port: 9090
            scheme: HTTP
          initialDelaySeconds: 10
          successThreshold: 1
        resources:
          limits:
            memory: 512Mi
            cpu: 500m
          requests:
            memory: 256Mi
            cpu: 250m
        securityContext:
          privileged: false
        startupProbe:
          failureThreshold: 30
          httpGet:
            path: /actuator/health/liveness
            port: 9090
          periodSeconds: 10
        volumeMounts:
        - mountPath: /etc/config
          name: config-volume
      volumes:
      - configMap:
          name: consumer-management-svc-config
        name: config-volume
